- hosts: proxmox
  tasks:
    - name: Remove PVE enterprise repository from sources list
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Add PVE no subscription repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        state: present

    - name: Upgrade all packages. Equivalent of "apt-get upgrade"
      apt:
        name: "*"
        state: latest

    - name: Upgrade current distro. Equivalent of "apt-get dist-upgrade".
      apt:
        upgrade: dist

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    
    - name: Install pip for python 3
      apt:
        name:
          - python3-pip
          - libguestfs-tools
          - python3-venv
        state: latest

    - name: Create a virtual environment named 'proxmox'
      command: python3 -m venv /root/venv/proxmox
      args:
        creates: /root/venv/proxmox

    - name: Activate virtual environment and run script
      shell: |
        source /root/venv/proxmox/bin/activate
        pip3 install proxmoxer requests
      args:
        executable: /bin/bash
